[package]
name = "big-brother"
version = "0.1.0"
edition = "2021"

[dependencies]
<<<<<<< HEAD
clap = { version = "4.5.23", features = ["derive"] }
=======
askama = "0.12.1"
axum = "0.8.1"
>>>>>>> 1da2bf3 (axum askama)
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["runtime-tokio", "sqlite"] }
tokio = { version = "1.42.0", features = ["full", "macros", "tokio-macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
